services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=dev
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SWAPI_BASE_URL=https://swapi.dev/api
      - PORT=8000
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: unless-stopped

volumes:
  redis_data:
